### ISSUE TITLE
Perft result

### ISSUE THREAD

**Issue by andersfylling** [notnil/chess#24]
Hi, it would be really interesting if you could provide PERFT results in the README file.

**Comment by notnil** [comment]
Great suggestion @andersfylling Merged #25

**Comment by andersfylling** [comment]
It would be great if the PERFT actually held the time as well. To compare it against other solutions.

And I think this should be a benchmark. PERFT takes a long time and should not be needed for every change in the repository if you use CI or pre-hooks to verify the changes.

https://github.com/notnil/chess/pull/25/files#diff-75d420b87dd31c20bada78fcfa3ad070R244

**Comment by Kerrigan29a** [comment]
I think `TestPerfResults` must be a test and not a benchmark because any change in the program must ensure it generates valid movements. If you want to limit some tests due to time limitations you can use the [short mode](https://golang.org/pkg/testing/#Short) as sugested [here](https://stackoverflow.com/a/50631395)

**Comment by andersfylling** [comment]
Except that you dont change the move generation every time. Its very possible to write small unit tests gor the move generation and then run perft as a 10min benchmark to validate the accuracy. But running perft as a test, every time. Thats a waste of resources and time.
